### PR TITLE
equivariant-neural-fields-gram-blogpost

### PR DESCRIPTION
**Pull request by Dafidofff**

### CODE REVIEW

**Comment by a-pouplin** [comment]
Thank you for your submission! Just so you know, in your [bib](assets/bibliography/2024-06-15-equivariant-neural-fields.bib) file, some references are missing. If you can quickly fix this, it would be great :)

**Comment by a-pouplin** [comment]
Thank you again for your submission! 
If you are willing to review another blog post, you can follow the guidelines [here](https://gram-blogposts.github.io/reviews/). You can also see how your own blog is rendering and you can still push, here, the missing bib references.

We will compile all the reviews and provide feedback on your submission by July 15th.

**Comment by Dafidofff** [comment]
Sorry for this late reply... I lost track. But I just fixed the .bib

**Comment by a-pouplin** [comment]
Your blog post has been accepted, congratulations! 

It will be featured on Gram-Blogpost on Monday, July 22nd. You will receive an email tonight with some feedback and instructions. You have until July 21st to make any improvements. If you are attending ICML in person, please inform us, as you can present your blog post as a poster at our workshop. Hopefully, see you next week in Vienna! :)

**Pull request merged**
