### PR TITLE
Learning Embedding Spaces with Metrics via Contrastive Learning

### PR DESCRIPTION
**Pull request by CynthiaFeeney**
Changes:

1. Added blog markdown file to `_posts`.
2. Added bibliography file to `assets/bibliography`.
3. Added figure image files to `assets/img`.

### CODE REVIEW

**Comment by a-pouplin** [comment]
We have successfully received your blog post. Thank you for your submission! 
If you are willing to review another blog post, you can follow the guidelines [here](https://gram-blogposts.github.io/reviews/).

We will compile all the reviews and provide feedback on your submission by July 15th. Thank you again!

**Comment by a-pouplin** [comment]
Your blog post has been accepted, congratulations! 

It will be featured on Gram-Blogpost on Monday, July 22nd. You will receive an email tonight with some feedback and instructions. You have until July 21st to make any improvements. If you are attending ICML in person, please inform us, as you can present your blog post as a poster at our workshop. Hopefully, see you next week in Vienna! :)

**Comment by CynthiaFeeney** [comment]
Great! I will be attending ICML in person and would love to present at the workshop. See you next week!

**Comment by CynthiaFeeney** [comment]
The latest commit addressed most of the requested revisions. The one thing I had trouble with was adding a table of contents, so if someone with more Jekyll experience could add that it would be appreciated.

**Pull request merged**
